# Generated by Django 4.2.23 on 2026-02-09 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='User gender', max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='User phone number', max_length=128, region=None)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('mother_name', models.CharField(blank=True, default='', max_length=255)),
                ('siblings', models.IntegerField(blank=True, help_text='Number of siblings', null=True)),
                ('family_type', models.CharField(blank=True, choices=[('nuclear', 'Nuclear'), ('joint', 'Joint')], default='', max_length=50)),
                ('family_status', models.CharField(blank=True, choices=[('middle_class', 'Middle Class'), ('upper_middle_class', 'Upper Middle Class'), ('rich', 'Rich')], default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='', help_text='Personal bio/description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
