# Generated by Django 4.2.23 on 2026-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_generate_sample_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Profiles this user is interested in', related_name='interested_by', to='user_profile.userprofile'),
        ),
    ]
